### PR TITLE
Add bootstrap site page and update maven plugins.

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by n0ha** [comment]
I'm having this error getting thrown on ```mvn clean package site```:

```
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.10:site (default) on project yuicompressor-ant-task: Server 'github' not found in settings
```

**Comment by hazendaz** [comment]
ok - to tie that into github, in your local .m2/settings.xml, it needs the following setup.  Then it can upload the resulting site to the ghpages for this project.

    <server>
      <id>github</id>
      <username>someuser</username>
      <password>somepassword</password>
    </server>

That also means it will replace what is out there now.

https://n0ha.github.io/yui-compressor-ant-task/

If you don't want that, remove the 'site-maven-plugin' and try again.  I don't see anything of real tangeble value currently on the ghpages.  It is just an auto generated page with a fork image, some basic information about the original auto generated ghpages site, and zip/tar of project.  All which is just as easily retrieve elsewhere or can be added back to the site generation here.  It may be worthwhile to see what this looks like to just comment out the said plugin for now and get the local generated site and review it.

**Comment by hazendaz** [comment]
Can I get an update on this?

**Comment by hazendaz** [comment]
@n0ha where you able to get past the issues this presented?  If not, I can do some work to switch out that site plugin for another that works better.  If willing to take this once that work is applied, I'll spin through and do some more bulid updates as things have certainly changed over the year.

**Comment by hazendaz** [comment]
@n0ha thanks.

**Pull request merged**
